
services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis


  redis:
    image: redis:latest
    expose:
      - "6379"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
    expose:
      - "5432"

volumes:
  static_volume:
  postgres_data: